### ISSUE TITLE
CSS: Print button overlaps with the left icons at the top bar in a small screens.

### ISSUE THREAD

**Issue by Sergio3** [JohnMcLear/ep_print#6]
Hello John,

I've noticed that the print button at the right container is overlapping the left container icons when I open Etherpad-lite in a small screen. I realized that when the print button is active the ".toolbar ul.menu_left" is taking the ".toolbar ul.menu_right" space. I solved this changing "right: 250px;" to "right: 300px;" at Etherpad-Lite's "src/static/pad.css":
```
.toolbar ul.menu_left {
    left: 0px;
    right: 300px;
}
```
But then when I restarted Etherpad-Lite these changes were not being implemented although "pad.css" contains the new data. I cleaned the navigator cache and restarted Etherpad-Lite several times with "/etc/init.d/etherpad-lite restart" and it seems like css is not refreshing properly.

Thank you very much again for all your work and support.

**Comment by JohnMcLear** [comment]
You should use the custom CSS files to make changes.
