### ISSUE TITLE
Long/Multiple line sentences won't break

### ISSUE THREAD

**Issue by Flauschie** [JohnMcLear/ep_print#7]
Long/Multiple line sentences won't break. I am able to reproduce this in two different etherpad setups. 

If I highlight the text within the preview window I can see the missing text (transparent) ranging beyond the page width.

**Comment by JohnMcLear** [comment]
Please print screen

**Comment by Flauschie** [comment]
![print_bug_etherpad](https://cloud.githubusercontent.com/assets/4295187/14943934/451b77fe-0fe6-11e6-9696-a885c365fc33.PNG)

Snippet from the text.

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce elementum ultrices nisl quis facilisis. Integer id pretium metus. Nullam non pellentesque velit, a varius ex. Maecenas dignissim sodales justo, posuere ultricies tortor varius a. Proin mattis turpis tellus. Phasellus in purus eu augue varius luctus vitae id odio. Suspendisse commodo rhoncus aliquet. Sed congue accumsan enim, ac varius libero dignissim ut.

Integer lobortis, massa molestie pharetra imperdiet, quam lorem venenatis turpis, eget sollicitudin justo orci sit amet nisi. Nam nec faucibus neque, et varius lacus. Duis sagittis finibus tortor. Mauris gravida purus id dui mattis, non ornare tortor malesuada. Vestibulum dictum ex id tellus aliquam feugiat vel a lorem. Suspendisse viverra luctus lacus. Nullam hendrerit lorem eu laoreet varius. Fusce at fermentum urna. Duis sodales bibendum justo vel porta.
```

**Comment by JohnMcLear** [comment]
Are you running ep_wrap or something?

**Comment by Flauschie** [comment]
I am not. Here is a list of the node_modules

```
ep_adminpads/
ep_align/
ep_author_hover/
ep_button_link/
ep_colors/
ep_comments_page/
ep_etherpad-lite -> ../src/
ep_headings2/
ep_horizontal_line/
ep_infopanel/
ep_message_all/
ep_page_view/
ep_previewimages/
ep_print/
ep_prompt_for_name/
ep_simpletextsearch/
ep_subscript/
ep_superscript/
ep_table_of_contents/
ep_tables2/
npm-local-cache/
```

**Comment by JohnMcLear** [comment]
can you try to remove all other plugins and isolate this so it's not a conflict?

**Comment by Flauschie** [comment]
Probably not before thursday. I will try it in a VM and report back if this issue persists or I know the plugin in conflict.

**Comment by JohnMcLear** [comment]
No need to close if you want to keep it open that's fine :)

**Comment by Flauschie** [comment]
Alright, wasn't able to go to sleep without trying to figure this out :-)

Uninstalled everything, bug still persists

```
ep_etherpad-lite -> ../src
etherpad etherpad 4096 Mai  1 23:55 ep_print
etherpad etherpad 4096 Mai  1 23:55 npm-local-cache
```

**Comment by JohnMcLear** [comment]
I can't replicate..  If i click the print button I get properly exported PDF as you expect...

**Comment by JohnMcLear** [comment]
Ah I see the problem now, this is a chrome specific problem.

**Comment by Flauschie** [comment]
Indeed, this is chrome related. Should have tried this earlier. But the font isn't as small as with firefox ;-)

**Comment by JohnMcLear** [comment]
Fixed

**Comment by Flauschie** [comment]
Sorry, but I have to reopen the issue.

Two problems with this fix:
1. I am not able to click url-links anymore (nothing happens) in both chrome/firefox
2. the printing result is different from what you can see in etherpad (see attachement). This is related to chrome again as it seems. I dont know if this is fixable but I wanted to tell you.

![print_bug_etherpad_new01](https://cloud.githubusercontent.com/assets/4295187/14944983/623c2986-1005-11e6-93a5-00bc8c33b7cd.PNG)
![print_bug_etherpad_new02](https://cloud.githubusercontent.com/assets/4295187/14944982/623ac0a0-1005-11e6-8100-4337faf0e68e.PNG)
